spring:
  datasource:
    enableMultiple: true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/sda
#    username: wyj
#    password: 317416
    multiple:
      #租户1配置
      - auto-commit: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sda
        username: wyj
        password: 317416
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 500000
        maximum-pool-size: 16
        minimum-idle: 5
        pool-name: HikariConnectPool
        connection-test-query: SELECT 1
        primary: true
        tenant: tenant1
      #租户2配置
      - auto-commit: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sda2
        username: wyj
        password: 317416
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 500000
        maximum-pool-size: 16
        minimum-idle: 5
        pool-name: HikariConnectPool
        connection-test-query: SELECT 1
        primary: false
        tenant: tenant2
  redis:
    cluster:
      #节点信息，ip:port，多个节点以英文逗号隔开
      nodes: localhost:6379,localhost:6380,localhost:6381
      #跨集群执行命令时要遵循的最大重定向数
      max-redirects: 6
    #密码
    password: 123123
    #客户端类型，固定格式
    client-type: jedis
    #连接超时时间，单位秒
    timeout: 1000
    #客户端连接配置
    jedis:
      pool:
        #连接池在给定时间可以分配的最大连接数。使用负值表示无限制。
        max-active: 20
        #当池耗尽时，连接分配在引发异常之前应该阻塞的最长时间。使用负值无限期阻止。
        max-wait: 60000
        #池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
        max-idle: 10
        #在池中维护的最小空闲连接数。只有当它和驱逐运行之间的时间都是正数时，这个设置才有效。
        min-idle: 0
    #多数据源配置
    datasource:
      #第一个数据源，租户编码
      tenant1:
        cluster:
          nodes: localhost:7100,localhost:7101,localhost:7102
        password: 123123
        #redis的数据库号，使用集群时必须为0
        database: 0
      #第二个数据源，租户编码
      tenant2:
        cluster:
          nodes: localhost:7200,localhost:7201,localhost:7202
        password: 123123
        #redis的数据库号，使用集群时必须为0
        database: 0



mybatis-plus:
  config-location: classpath:mybatis-config.xml
  # 扫描 mapper.xml
  mapper-locations: classpath:mapper/**/*.xml
